-- SCRIPT 01: CRIAÇÃO DO ESQUEMA (DDL)
-- Modelo Lógico: 3ª Forma Normal (3FN) - Taça Interbairros

-- Criação do Banco de Dados
CREATE DATABASE IF NOT EXISTS taca_interbairros;
USE taca_interbairros;

-- 1. Tabela CAMPEONATO (PK simples)
CREATE TABLE CAMPEONATO (
    Camp_ID INT PRIMARY KEY AUTO_INCREMENT,
    Camp_Nome VARCHAR(100) NOT NULL UNIQUE,
    Camp_Ano INT NOT NULL,
    Camp_Formato VARCHAR(50)
);

-- 2. Tabela ESTADIO (PK simples)
CREATE TABLE ESTADIO (
    Est_ID INT PRIMARY KEY AUTO_INCREMENT,
    Est_Nome VARCHAR(100) NOT NULL UNIQUE,
    Est_Endereco VARCHAR(255) NOT NULL,
    Est_Capacidade INT NOT NULL
);

-- 3. Tabela ARBITRO (PK simples)
CREATE TABLE ARBITRO (
    Arb_ID INT PRIMARY KEY AUTO_INCREMENT,
    Arb_Nome VARCHAR(100) NOT NULL,
    Arb_Contato VARCHAR(50) UNIQUE
);

-- 4. Tabela TIME (FK para CAMPEONATO)
CREATE TABLE TIME (
    Time_ID INT PRIMARY KEY AUTO_INCREMENT,
    Camp_ID INT NOT NULL,
    Time_Nome VARCHAR(100) NOT NULL UNIQUE,
    Time_Cores VARCHAR(50) NOT NULL,
    Time_Tecnico VARCHAR(100) NOT NULL,
    FOREIGN KEY (Camp_ID) REFERENCES CAMPEONATO(Camp_ID)
);

-- 5. Tabela JOGADOR (FK para TIME)
CREATE TABLE JOGADOR (
    Jog_Matricula INT PRIMARY KEY,
    Time_ID INT NOT NULL,
    Jog_Nome VARCHAR(100) NOT NULL,
    Jog_Posicao VARCHAR(50) NOT NULL,
    Jog_Dt_Nascimento DATE NOT NULL,
    Jog_Status_Suspensao BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (Time_ID) REFERENCES TIME(Time_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 6. Tabela PARTIDA (FKs para Estádio, Árbitro e 2 Times)
CREATE TABLE PARTIDA (
    Part_ID INT PRIMARY KEY AUTO_INCREMENT,
    Est_ID INT NOT NULL,
    Arb_ID INT NOT NULL,
    Time_Casa_ID INT NOT NULL,
    Time_Visitante_ID INT NOT NULL,
    Part_Data DATE NOT NULL,
    Part_Hora TIME NOT NULL,
    Part_Placar_Casa INT NOT NULL DEFAULT 0,
    Part_Placar_Visitante INT NOT NULL DEFAULT 0,
    FOREIGN KEY (Est_ID) REFERENCES ESTADIO(Est_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (Arb_ID) REFERENCES ARBITRO(Arb_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (Time_Casa_ID) REFERENCES TIME(Time_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (Time_Visitante_ID) REFERENCES TIME(Time_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CHECK (Time_Casa_ID <> Time_Visitante_ID)
);

-- 7. Tabela EVENTO_PARTIDA (Tabela Associativa com Chave Composta)
CREATE TABLE EVENTO_PARTIDA (
    Part_ID INT,
    Event_ID INT AUTO_INCREMENT,
    Jog_Matricula INT NOT NULL,
    Event_Tipo VARCHAR(50) NOT NULL,
    Event_Minuto INT,
    PRIMARY KEY (Part_ID, Event_ID),
    FOREIGN KEY (Part_ID) REFERENCES PARTIDA(Part_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Jog_Matricula) REFERENCES JOGADOR(Jog_Matricula) ON DELETE RESTRICT ON UPDATE CASCADE
);
